---
apiVersion: getambassador.io/v1
kind: Mapping
metadata:
  name: demo-ui
spec:
  prefix: /
  service: demo:5000
---
apiVersion: getambassador.io/v1
kind: Mapping
metadata:
  name: demo-backend
spec:
  prefix: /backend/
  service: demo:8080
  labels:
    ambassador:
      - request_label:
        - backend
---
apiVersion: v1
kind: Service
metadata:
  name: demo
spec:
  ports:
  - name: ui
    port: 5000
    targetPort: 5000
  - name: backend
    port: 8080
    targetPort: 8080
  selector:
    app: demo
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: demo
    spec:
      containers:
      - name: demo-ui
        image: quay.io/datawire/demo:ui-0.1.5
        ports:
        - name: http
          containerPort: 5000
      - name: quote
        image: quay.io/datawire/demo:backend-0.1.5
        ports:
        - name: http
          containerPort: 8080
        resources:
          limits:
            cpu: "0.1"
            memory: 100Mi
